export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER_WITH_JWT = "LOGIN_USER_WITH_JWT";

export const FETCH_CURRENT_USER_DATA = "FETCH_CURRENT_USER_DATA";
export const FETCH_ALL_USERS_DATA = "FETCH_ALL_USERS_DATA";
export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_MODELS_DATA = "FETCH_USER_MODELS_DATA";
export const FETCH_USER_MODEL_DATA = "FETCH_USER_MODEL_DATA";

export const DELETE_USER_DATA = "DELETE_USER_DATA";
export const DELETE_MODEL_DATA = "DELETE_MODEL_DATA";

export const FETCH_FILE_TO_SEND = "FETCH_FILE_TO_SEND";
export const SEND_FILE = "SEND_FILE";
