export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER_WITH_JWT = "LOGIN_USER_WITH_JWT";

export const FETCH_CURRENT_USER_DATA = "FETCH_CURRENT_USER_DATA";
export const FETCH_ALL_USERS_DATA = "FETCH_ALL_USERS_DATA";
export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_MODELS_DATA = "FETCH_USER_MODELS_DATA";
export const FETCH_USER_MODEL_DATA = "FETCH_USER_MODEL_DATA";

export const DELETE_USER_DATA = "DELETE_USER_DATA";
export const DELETE_MODEL_DATA = "DELETE_MODEL_DATA";

export const FETCH_FILE_TO_SEND = "FETCH_FILE_TO_SEND";
export const SEND_FILE = "SEND_FILE";

export const BUSY_DIALOG_SHOW = "BUSY_DIALOG_SHOW";
export const BUSY_DIALOG_HIDE = "BUSY_DIALOG_HIDE";

export const LOGIN_DIALOG_SHOW = "LOGIN_DIALOG_SHOW";
export const LOGIN_DIALOG_HIDE = "LOGIN_DIALOG_HIDE";
